apiVersion: apps/v1
kind: Deployment 
metadata:
  name: cart-page-rs
  namespace: pranavas-ns 
spec:
  replicas: 3
  selector:
    matchLabels:
      web: cart
  template:
    metadata:
      labels:
        web: cart 
    spec: 
      containers:
        - name: cart-container
          image: muralisocial123/cart/page/test:1.0
          ports:
            - containerPort: 3000